/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotInfo
 */
export interface RobotInfo {
    /**
     * 
     * @type {string}
     * @memberof RobotInfo
     */
    robotId: string;
    /**
     * 
     * @type {string}
     * @memberof RobotInfo
     */
    pool: string;
    /**
     * 
     * @type {boolean}
     * @memberof RobotInfo
     */
    isIdleOnPool: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RobotInfo
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RobotInfo
     */
    status: RobotInfoStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof RobotInfo
     */
    errorInfo?: object;
}


/**
 * @export
 */
export const RobotInfoStatusEnum = {
    Idle: 'IDLE',
    Busy: 'BUSY',
    Error: 'ERROR'
} as const;
export type RobotInfoStatusEnum = typeof RobotInfoStatusEnum[keyof typeof RobotInfoStatusEnum];


/**
 * Check if a given object implements the RobotInfo interface.
 */
export function instanceOfRobotInfo(value: object): value is RobotInfo {
    if (!('robotId' in value) || value['robotId'] === undefined) return false;
    if (!('pool' in value) || value['pool'] === undefined) return false;
    if (!('isIdleOnPool' in value) || value['isIdleOnPool'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RobotInfoFromJSON(json: any): RobotInfo {
    return RobotInfoFromJSONTyped(json, false);
}

export function RobotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'robotId': json['robotId'],
        'pool': json['pool'],
        'isIdleOnPool': json['isIdleOnPool'],
        'createdAt': (new Date(json['createdAt'])),
        'status': json['status'],
        'errorInfo': json['errorInfo'] == null ? undefined : json['errorInfo'],
    };
}

export function RobotInfoToJSON(json: any): RobotInfo {
    return RobotInfoToJSONTyped(json, false);
}

export function RobotInfoToJSONTyped(value?: RobotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'robotId': value['robotId'],
        'pool': value['pool'],
        'isIdleOnPool': value['isIdleOnPool'],
        'createdAt': ((value['createdAt']).toISOString()),
        'status': value['status'],
        'errorInfo': value['errorInfo'],
    };
}

