/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotErrorPayloadReq
 */
export interface RobotErrorPayloadReq {
    /**
     * 
     * @type {string}
     * @memberof RobotErrorPayloadReq
     */
    errorCode: string;
    /**
     * 
     * @type {string}
     * @memberof RobotErrorPayloadReq
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof RobotErrorPayloadReq
     */
    description: string;
}

/**
 * Check if a given object implements the RobotErrorPayloadReq interface.
 */
export function instanceOfRobotErrorPayloadReq(value: object): value is RobotErrorPayloadReq {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function RobotErrorPayloadReqFromJSON(json: any): RobotErrorPayloadReq {
    return RobotErrorPayloadReqFromJSONTyped(json, false);
}

export function RobotErrorPayloadReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotErrorPayloadReq {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'description': json['description'],
    };
}

export function RobotErrorPayloadReqToJSON(json: any): RobotErrorPayloadReq {
    return RobotErrorPayloadReqToJSONTyped(json, false);
}

export function RobotErrorPayloadReqToJSONTyped(value?: RobotErrorPayloadReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'message': value['message'],
        'description': value['description'],
    };
}
