/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotCommandResp
 */
export interface RobotCommandResp {
    /**
     * 
     * @type {string}
     * @memberof RobotCommandResp
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof RobotCommandResp
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof RobotCommandResp
     */
    data?: object;
}

/**
 * Check if a given object implements the RobotCommandResp interface.
 */
export function instanceOfRobotCommandResp(value: object): value is RobotCommandResp {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RobotCommandRespFromJSON(json: any): RobotCommandResp {
    return RobotCommandRespFromJSONTyped(json, false);
}

export function RobotCommandRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotCommandResp {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function RobotCommandRespToJSON(json: any): RobotCommandResp {
    return RobotCommandRespToJSONTyped(json, false);
}

export function RobotCommandRespToJSONTyped(value?: RobotCommandResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': value['data'],
    };
}

