/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadResult
 */
export interface UploadResult {
    /**
     * 
     * @type {boolean}
     * @memberof UploadResult
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof UploadResult
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadResult
     */
    hash?: string;
}

/**
 * Check if a given object implements the UploadResult interface.
 */
export function instanceOfUploadResult(value: object): value is UploadResult {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function UploadResultFromJSON(json: any): UploadResult {
    return UploadResultFromJSONTyped(json, false);
}

export function UploadResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'message': json['message'] == null ? undefined : json['message'],
        'hash': json['hash'] == null ? undefined : json['hash'],
    };
}

export function UploadResultToJSON(json: any): UploadResult {
    return UploadResultToJSONTyped(json, false);
}

export function UploadResultToJSONTyped(value?: UploadResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'message': value['message'],
        'hash': value['hash'],
    };
}

