/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IaModelsResp,
  IaReq,
  IaResp,
} from '../models/index';
import {
    IaModelsRespFromJSON,
    IaModelsRespToJSON,
    IaReqFromJSON,
    IaReqToJSON,
    IaRespFromJSON,
    IaRespToJSON,
} from '../models/index';

export interface RobotControllerRunIaRequest {
    iaReq: IaReq;
}

/**
 * 
 */
export class IaApi extends runtime.BaseAPI {

    /**
     */
    async robotControllerIaModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IaModelsResp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/ia/models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IaModelsRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerIaModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IaModelsResp> {
        const response = await this.robotControllerIaModelsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerRunIaRaw(requestParameters: RobotControllerRunIaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IaResp>> {
        if (requestParameters['iaReq'] == null) {
            throw new runtime.RequiredError(
                'iaReq',
                'Required parameter "iaReq" was null or undefined when calling robotControllerRunIa().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/ia/run`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IaReqToJSON(requestParameters['iaReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IaRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerRunIa(requestParameters: RobotControllerRunIaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IaResp> {
        const response = await this.robotControllerRunIaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
