/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RobotCommandReq,
  RobotCommandResp,
  RobotCreateResp,
  RobotErrorReq,
  RobotInfo,
  UploadResult,
} from '../models/index';
import {
    RobotCommandReqFromJSON,
    RobotCommandReqToJSON,
    RobotCommandRespFromJSON,
    RobotCommandRespToJSON,
    RobotCreateRespFromJSON,
    RobotCreateRespToJSON,
    RobotErrorReqFromJSON,
    RobotErrorReqToJSON,
    RobotInfoFromJSON,
    RobotInfoToJSON,
    UploadResultFromJSON,
    UploadResultToJSON,
} from '../models/index';

export interface RobotControllerCreateRequest {
    pool: string;
}

export interface RobotControllerDeleteRequest {
    id: string;
}

export interface RobotControllerDeleteFileRequest {
    hash: string;
}

export interface RobotControllerErrorRequest {
    robotErrorReq: RobotErrorReq;
}

export interface RobotControllerRunRequest {
    robotCommandReq: RobotCommandReq;
}

export interface RobotControllerScreenshotRequest {
    id: string;
}

export interface RobotControllerUploadRequest {
    file: Blob;
}

/**
 * 
 */
export class PuppeteerRobotApi extends runtime.BaseAPI {

    /**
     */
    async robotControllerCreateRaw(requestParameters: RobotControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotCreateResp>> {
        if (requestParameters['pool'] == null) {
            throw new runtime.RequiredError(
                'pool',
                'Required parameter "pool" was null or undefined when calling robotControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/create/{pool}`;
        urlPath = urlPath.replace(`{${"pool"}}`, encodeURIComponent(String(requestParameters['pool'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotCreateRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerCreate(requestParameters: RobotControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotCreateResp> {
        const response = await this.robotControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerDeleteRaw(requestParameters: RobotControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling robotControllerDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async robotControllerDelete(requestParameters: RobotControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.robotControllerDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async robotControllerDeleteFileRaw(requestParameters: RobotControllerDeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadResult>> {
        if (requestParameters['hash'] == null) {
            throw new runtime.RequiredError(
                'hash',
                'Required parameter "hash" was null or undefined when calling robotControllerDeleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/file/delete/{hash}`;
        urlPath = urlPath.replace(`{${"hash"}}`, encodeURIComponent(String(requestParameters['hash'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadResultFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerDeleteFile(requestParameters: RobotControllerDeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadResult> {
        const response = await this.robotControllerDeleteFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerErrorRaw(requestParameters: RobotControllerErrorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotCommandResp>> {
        if (requestParameters['robotErrorReq'] == null) {
            throw new runtime.RequiredError(
                'robotErrorReq',
                'Required parameter "robotErrorReq" was null or undefined when calling robotControllerError().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/error`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RobotErrorReqToJSON(requestParameters['robotErrorReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotCommandRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerError(requestParameters: RobotControllerErrorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotCommandResp> {
        const response = await this.robotControllerErrorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RobotInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RobotInfoFromJSON));
    }

    /**
     */
    async robotControllerList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RobotInfo>> {
        const response = await this.robotControllerListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerRunRaw(requestParameters: RobotControllerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotCommandResp>> {
        if (requestParameters['robotCommandReq'] == null) {
            throw new runtime.RequiredError(
                'robotCommandReq',
                'Required parameter "robotCommandReq" was null or undefined when calling robotControllerRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/run`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RobotCommandReqToJSON(requestParameters['robotCommandReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotCommandRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerRun(requestParameters: RobotControllerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotCommandResp> {
        const response = await this.robotControllerRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerScreenshotRaw(requestParameters: RobotControllerScreenshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotCommandResp>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling robotControllerScreenshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/screenshot/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotCommandRespFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerScreenshot(requestParameters: RobotControllerScreenshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotCommandResp> {
        const response = await this.robotControllerScreenshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerUploadRaw(requestParameters: RobotControllerUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadResult>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling robotControllerUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/puppeteer-robot/file/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadResultFromJSON(jsonValue));
    }

    /**
     */
    async robotControllerUpload(requestParameters: RobotControllerUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadResult> {
        const response = await this.robotControllerUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async robotControllerVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/puppeteer-robot/version`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async robotControllerVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.robotControllerVersionRaw(initOverrides);
        return await response.value();
    }

}
