/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IaModelsResp
 */
export interface IaModelsResp {
    /**
     * 
     * @type {boolean}
     * @memberof IaModelsResp
     */
    ok: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof IaModelsResp
     */
    models?: Array<string>;
}

/**
 * Check if a given object implements the IaModelsResp interface.
 */
export function instanceOfIaModelsResp(value: object): value is IaModelsResp {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function IaModelsRespFromJSON(json: any): IaModelsResp {
    return IaModelsRespFromJSONTyped(json, false);
}

export function IaModelsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): IaModelsResp {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'models': json['models'] == null ? undefined : json['models'],
    };
}

export function IaModelsRespToJSON(json: any): IaModelsResp {
    return IaModelsRespToJSONTyped(json, false);
}

export function IaModelsRespToJSONTyped(value?: IaModelsResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'models': value['models'],
    };
}

