/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IaResp
 */
export interface IaResp {
    /**
     * 
     * @type {boolean}
     * @memberof IaResp
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof IaResp
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof IaResp
     */
    html?: string;
    /**
     * 
     * @type {string}
     * @memberof IaResp
     */
    response?: string;
    /**
     * 
     * @type {string}
     * @memberof IaResp
     */
    prompt?: string;
}

/**
 * Check if a given object implements the IaResp interface.
 */
export function instanceOfIaResp(value: object): value is IaResp {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function IaRespFromJSON(json: any): IaResp {
    return IaRespFromJSONTyped(json, false);
}

export function IaRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): IaResp {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'message': json['message'] == null ? undefined : json['message'],
        'html': json['html'] == null ? undefined : json['html'],
        'response': json['response'] == null ? undefined : json['response'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
    };
}

export function IaRespToJSON(json: any): IaResp {
    return IaRespToJSONTyped(json, false);
}

export function IaRespToJSONTyped(value?: IaResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'message': value['message'],
        'html': value['html'],
        'response': value['response'],
        'prompt': value['prompt'],
    };
}

