/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IaReq
 */
export interface IaReq {
    /**
     * 
     * @type {string}
     * @memberof IaReq
     */
    robotId: string;
    /**
     * 
     * @type {string}
     * @memberof IaReq
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof IaReq
     */
    model: string;
}

/**
 * Check if a given object implements the IaReq interface.
 */
export function instanceOfIaReq(value: object): value is IaReq {
    if (!('robotId' in value) || value['robotId'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function IaReqFromJSON(json: any): IaReq {
    return IaReqFromJSONTyped(json, false);
}

export function IaReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): IaReq {
    if (json == null) {
        return json;
    }
    return {
        
        'robotId': json['robotId'],
        'query': json['query'],
        'model': json['model'],
    };
}

export function IaReqToJSON(json: any): IaReq {
    return IaReqToJSONTyped(json, false);
}

export function IaReqToJSONTyped(value?: IaReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'robotId': value['robotId'],
        'query': value['query'],
        'model': value['model'],
    };
}

