/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotErrorReq
 */
export interface RobotErrorReq {
    /**
     * 
     * @type {string}
     * @memberof RobotErrorReq
     */
    robotId: string;
}

/**
 * Check if a given object implements the RobotErrorReq interface.
 */
export function instanceOfRobotErrorReq(value: object): value is RobotErrorReq {
    if (!('robotId' in value) || value['robotId'] === undefined) return false;
    return true;
}

export function RobotErrorReqFromJSON(json: any): RobotErrorReq {
    return RobotErrorReqFromJSONTyped(json, false);
}

export function RobotErrorReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotErrorReq {
    if (json == null) {
        return json;
    }
    return {
        
        'robotId': json['robotId'],
    };
}

export function RobotErrorReqToJSON(json: any): RobotErrorReq {
    return RobotErrorReqToJSONTyped(json, false);
}

export function RobotErrorReqToJSONTyped(value?: RobotErrorReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'robotId': value['robotId'],
    };
}

