/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotCreateResp
 */
export interface RobotCreateResp {
    /**
     * 
     * @type {boolean}
     * @memberof RobotCreateResp
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof RobotCreateResp
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof RobotCreateResp
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RobotCreateResp
     */
    robotId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RobotCreateResp
     */
    isFromPool?: boolean;
}

/**
 * Check if a given object implements the RobotCreateResp interface.
 */
export function instanceOfRobotCreateResp(value: object): value is RobotCreateResp {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function RobotCreateRespFromJSON(json: any): RobotCreateResp {
    return RobotCreateRespFromJSONTyped(json, false);
}

export function RobotCreateRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotCreateResp {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'message': json['message'] == null ? undefined : json['message'],
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'robotId': json['robotId'] == null ? undefined : json['robotId'],
        'isFromPool': json['isFromPool'] == null ? undefined : json['isFromPool'],
    };
}

export function RobotCreateRespToJSON(json: any): RobotCreateResp {
    return RobotCreateRespToJSONTyped(json, false);
}

export function RobotCreateRespToJSONTyped(value?: RobotCreateResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'message': value['message'],
        'errorCode': value['errorCode'],
        'robotId': value['robotId'],
        'isFromPool': value['isFromPool'],
    };
}

