/* tslint:disable */
/* eslint-disable */
/**
 * Puppeteer Robot API
 * Puppeteer Robot API
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotCommandReq
 */
export interface RobotCommandReq {
    /**
     * 
     * @type {string}
     * @memberof RobotCommandReq
     */
    robotId: string;
    /**
     * 
     * @type {string}
     * @memberof RobotCommandReq
     */
    command: string;
}

/**
 * Check if a given object implements the RobotCommandReq interface.
 */
export function instanceOfRobotCommandReq(value: object): value is RobotCommandReq {
    if (!('robotId' in value) || value['robotId'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function RobotCommandReqFromJSON(json: any): RobotCommandReq {
    return RobotCommandReqFromJSONTyped(json, false);
}

export function RobotCommandReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotCommandReq {
    if (json == null) {
        return json;
    }
    return {
        
        'robotId': json['robotId'],
        'command': json['command'],
    };
}

export function RobotCommandReqToJSON(json: any): RobotCommandReq {
    return RobotCommandReqToJSONTyped(json, false);
}

export function RobotCommandReqToJSONTyped(value?: RobotCommandReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'robotId': value['robotId'],
        'command': value['command'],
    };
}

